name: Maven Build

on:
  push:
    branches:
      - master
      - develop
      - develop-*
  workflow_dispatch:

jobs:

  build-arm64:
    runs-on: macos-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17
        architecture: aarch64

    - name: Cache maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn -B package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        platforms: linux/arm64
        push: true
        tags: ${{vars.IMAGE_NAME}}:latest, ${{vars.IMAGE_NAME}}:${{ github.sha }}

  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17
        architecture: x64

    - name: Cache maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn -B package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        platforms: linux/amd64
        push: true
        tags: ${{vars.IMAGE_NAME}}:latest, ${{vars.IMAGE_NAME}}:${{ github.sha }}

